version: "3.9"

services:
  postgresql:
    image: postgres:16-alpine
    volumes:
      - ./local/volumes/postgresql:/var/lib/postgresql/data
    ports:
      - 5432:5432
    container_name: ${PROJECT_NAME}-postgresql
    environment:
      - TZ=UTC
      - POSTGRES_USER=administrator
      - POSTGRES_PASSWORD=P#ssw0rd
    deploy:
      resources:
        limits:
          cpus: "0.5"
          memory: 512M
    networks:
      - ecommerce-platform

networks:
  ecommerce-platform:
