version: "3.9"

services:
  ecommerce:
    build:
      context: .
      dockerfile: containerfile.dev
      args:
        - APP_PATH=ecommerce
        - APP_NAME=ECommerce.Api
    container_name: ecommerce
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    labels:
      - app=ecommerce
      - name=ecommerce
    ports:
      - 10002:80
    deploy:
      resources:
        limits:
          cpus: "0.5"
          memory: 512M
    networks:
      - ecommerce-platform

networks:
  ecommerce-platform:
