version: "3.8"

services:
  bookstore-web:
    image: ${PROJECT_NAME}-bookstore-web:${ENV:-latest}
    container_name: ${PROJECT_NAME}-${ENV}-bookstore-web
    build:
      context: services/bookstore-web
      dockerfile: ./Dockerfile.${ENV}
    ports:
      - 3000:3000
    depends_on:
      - products.api

  products.api:
    image: ${PROJECT_NAME}-products-api:${ENV:-latest}
    container_name: ${PROJECT_NAME}-${ENV}-products-api
    build:
      context: .
      dockerfile: services/products/PRODUCTS.API/Dockerfile
    ports:
      - 5012:5012
