version: "3.8"

services:
  products-api:
    image: ${PROJECT_NAME}-products-api:${ENV:-latest}
    container_name: ${PROJECT_NAME}-${ENV}-products-api
    build:
      context: .
      dockerfile: services/products/PRODUCTS.API/Dockerfile
    environment:
      - ConnectionStrings__DefaultConnectionString=User ID=postgres;Password=postgres;Host=db;Port=5432;Database=product-service;
    ports:
      - 5012:80
