CREATE TABLE IF NOT EXISTS "__EFMigrationsHistory" (
    migration_id character varying(150) NOT NULL,
    product_version character varying(32) NOT NULL,
    CONSTRAINT pk___ef_migrations_history PRIMARY KEY (migration_id)
);

START TRANSACTION;


DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "migration_id" = '20240925091247_Initialize') THEN
    CREATE TABLE inbox_state (
        id bigint GENERATED BY DEFAULT AS IDENTITY,
        message_id uuid NOT NULL,
        consumer_id uuid NOT NULL,
        lock_id uuid NOT NULL,
        row_version bytea,
        received timestamp with time zone NOT NULL,
        receive_count integer NOT NULL,
        expiration_time timestamp with time zone,
        consumed timestamp with time zone,
        delivered timestamp with time zone,
        last_sequence_number bigint,
        CONSTRAINT pk_inbox_state PRIMARY KEY (id),
        CONSTRAINT ak_inbox_state_message_id_consumer_id UNIQUE (message_id, consumer_id)
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "migration_id" = '20240925091247_Initialize') THEN
    CREATE TABLE outbox_message (
        sequence_number bigint GENERATED BY DEFAULT AS IDENTITY,
        enqueue_time timestamp with time zone,
        sent_time timestamp with time zone NOT NULL,
        headers text,
        properties text,
        inbox_message_id uuid,
        inbox_consumer_id uuid,
        outbox_id uuid,
        message_id uuid NOT NULL,
        content_type character varying(256) NOT NULL,
        message_type text NOT NULL,
        body text NOT NULL,
        conversation_id uuid,
        correlation_id uuid,
        initiator_id uuid,
        request_id uuid,
        source_address character varying(256),
        destination_address character varying(256),
        response_address character varying(256),
        fault_address character varying(256),
        expiration_time timestamp with time zone,
        CONSTRAINT pk_outbox_message PRIMARY KEY (sequence_number)
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "migration_id" = '20240925091247_Initialize') THEN
    CREATE TABLE outbox_state (
        outbox_id uuid NOT NULL,
        lock_id uuid NOT NULL,
        row_version bytea,
        created timestamp with time zone NOT NULL,
        delivered timestamp with time zone,
        last_sequence_number bigint,
        CONSTRAINT pk_outbox_state PRIMARY KEY (outbox_id)
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "migration_id" = '20240925091247_Initialize') THEN
    CREATE INDEX ix_inbox_state_delivered ON inbox_state (delivered);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "migration_id" = '20240925091247_Initialize') THEN
    CREATE INDEX ix_outbox_message_enqueue_time ON outbox_message (enqueue_time);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "migration_id" = '20240925091247_Initialize') THEN
    CREATE INDEX ix_outbox_message_expiration_time ON outbox_message (expiration_time);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "migration_id" = '20240925091247_Initialize') THEN
    CREATE UNIQUE INDEX ix_outbox_message_inbox_message_id_inbox_consumer_id_sequence_ ON outbox_message (inbox_message_id, inbox_consumer_id, sequence_number);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "migration_id" = '20240925091247_Initialize') THEN
    CREATE UNIQUE INDEX ix_outbox_message_outbox_id_sequence_number ON outbox_message (outbox_id, sequence_number);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "migration_id" = '20240925091247_Initialize') THEN
    CREATE INDEX ix_outbox_state_created ON outbox_state (created);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "migration_id" = '20240925091247_Initialize') THEN
    INSERT INTO "__EFMigrationsHistory" (migration_id, product_version)
    VALUES ('20240925091247_Initialize', '8.0.1');
    END IF;
END $EF$;
COMMIT;

