// <auto-generated />
using ECommerce.Catalog.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace ECommerce.Catalog.DbMigrator.PostgreSQL.Migrations
{
    [DbContext(typeof(CatalogDbContext))]
    partial class CatalogDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("ECommerce.Catalog.Domain.AggregatesModel.AdministrativeUnits.District", b =>
                {
                    b.Property<string>("Name")
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<string>("Code")
                        .HasColumnType("text")
                        .HasColumnName("code");

                    b.HasKey("Name")
                        .HasName("pk_districts");

                    b.ToTable("districts", (string)null);
                });

            modelBuilder.Entity("ECommerce.Catalog.Domain.AggregatesModel.AdministrativeUnits.Province", b =>
                {
                    b.Property<string>("Name")
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<string>("Code")
                        .HasColumnType("text")
                        .HasColumnName("code");

                    b.HasKey("Name")
                        .HasName("pk_provinces");

                    b.ToTable("provinces", (string)null);
                });

            modelBuilder.Entity("ECommerce.Catalog.Domain.AggregatesModel.AdministrativeUnits.Ward", b =>
                {
                    b.Property<string>("Name")
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<string>("Code")
                        .HasColumnType("text")
                        .HasColumnName("code");

                    b.HasKey("Name")
                        .HasName("pk_wards");

                    b.ToTable("wards", (string)null);
                });
#pragma warning restore 612, 618
        }
    }
}
